#!/bin/sh
# Minimal Gradle wrapper launcher (official scripts get generated by `gradle wrapper`).
APP_HOME=$(dirname "$0")
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ -n "$JAVA_HOME" ]; then
  "$JAVA_HOME/bin/java" -cp "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
else
  java -cp "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
fi
