@ECHO OFF
@rem Minimal Gradle wrapper launcher (official scripts get generated by `gradle wrapper`).
SET APP_HOME=%~dp0
"%JAVA_HOME%\bin\java.exe" -cp "%APP_HOME%gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*
if not "%JAVA_HOME%" == "" goto end
java -cp "%APP_HOME%gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*
:end
